import type { Column } from '@/components/shared/data-table';
import type { ProcurementRequest } from '@/data/types';
import type { EntityConfig } from './types';

type RequestRow = ProcurementRequest & Record<string, unknown>;

const columns: Column<RequestRow>[] = [
  { key: 'id', label: 'ID', sortable: true, className: 'font-mono text-xs' },
  { key: 'title', label: 'Title', sortable: true },
  { key: 'category', label: 'Category', sortable: true },
  {
    key: 'value',
    label: 'Value',
    sortable: true,
    render: (r) => `${r.currency} ${r.value.toLocaleString()}`,
  },
  { key: 'status', label: 'Status', sortable: true },
  { key: 'buyingChannel', label: 'Channel', sortable: true },
  { key: 'priority', label: 'Priority', sortable: true },
  {
    key: 'isOverdue',
    label: 'Overdue',
    render: (r) =>
      r.isOverdue ? (
        <span className="text-red-600 text-xs font-medium">Yes</span>
      ) : (
        <span className="text-gray-400 text-xs">No</span>
      ),
  },
];

export const requestsConfig: EntityConfig<'request'> = {
  key: 'request',
  columns,
  getId: (r) => r.id,
  getDisplayLabel: (r) => `${r.id} — ${r.title}`,
  defaultNew: () => ({
    id: `REQ-${new Date().getFullYear()}-${Math.floor(Math.random() * 9000 + 1000)}`,
    title: '',
    description: '',
    category: 'goods',
    status: 'draft',
    priority: 'medium',
    value: 0,
    currency: 'EUR',
    requestorId: '',
    ownerId: '',
    buyingChannel: 'business-led',
    commodityCode: '',
    commodityCodeLabel: '',
    costCentre: '',
    budgetOwner: '',
    businessJustification: '',
    deliveryDate: '',
    isUrgent: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    daysInStage: 0,
    isOverdue: false,
    referBackCount: 0,
  }),
  fields: [
    { key: 'id', label: 'ID', type: 'text', required: true, readOnly: true },
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'textarea' },
    {
      key: 'category',
      label: 'Category',
      type: 'select',
      required: true,
      options: [
        { value: 'goods', label: 'Goods' },
        { value: 'services', label: 'Services' },
        { value: 'software', label: 'Software' },
        { value: 'consulting', label: 'Consulting' },
        { value: 'contingent-labour', label: 'Contingent labour' },
        { value: 'contract-renewal', label: 'Contract renewal' },
        { value: 'supplier-onboarding', label: 'Supplier onboarding' },
        { value: 'catalogue', label: 'Catalogue' },
      ],
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      options: [
        { value: 'draft', label: 'Draft' },
        { value: 'intake', label: 'Intake' },
        { value: 'validation', label: 'Validation' },
        { value: 'approval', label: 'Approval' },
        { value: 'sourcing', label: 'Sourcing' },
        { value: 'contracting', label: 'Contracting' },
        { value: 'po', label: 'PO' },
        { value: 'receipt', label: 'Receipt' },
        { value: 'invoice', label: 'Invoice' },
        { value: 'payment', label: 'Payment' },
        { value: 'completed', label: 'Completed' },
        { value: 'cancelled', label: 'Cancelled' },
        { value: 'referred-back', label: 'Referred back' },
      ],
    },
    {
      key: 'priority',
      label: 'Priority',
      type: 'select',
      options: [
        { value: 'low', label: 'Low' },
        { value: 'medium', label: 'Medium' },
        { value: 'high', label: 'High' },
        { value: 'urgent', label: 'Urgent' },
      ],
    },
    { key: 'value', label: 'Value', type: 'number', required: true, min: 0 },
    { key: 'currency', label: 'Currency', type: 'text' },
    { key: 'requestorId', label: 'Requestor User ID', type: 'text' },
    { key: 'ownerId', label: 'Owner User ID', type: 'text' },
    { key: 'supplierId', label: 'Supplier ID (optional)', type: 'text' },
    { key: 'contractId', label: 'Contract ID (optional)', type: 'text' },
    { key: 'poId', label: 'PO ID (optional)', type: 'text' },
    {
      key: 'buyingChannel',
      label: 'Buying Channel',
      type: 'select',
      options: [
        { value: 'procurement-led', label: 'Procurement-led' },
        { value: 'business-led', label: 'Business-led' },
        { value: 'direct-po', label: 'Direct PO' },
        { value: 'framework-call-off', label: 'Framework call-off' },
        { value: 'catalogue', label: 'Catalogue' },
      ],
    },
    { key: 'commodityCode', label: 'Commodity Code', type: 'text' },
    { key: 'commodityCodeLabel', label: 'Commodity Label', type: 'text' },
    { key: 'costCentre', label: 'Cost Centre', type: 'text' },
    { key: 'budgetOwner', label: 'Budget Owner', type: 'text' },
    { key: 'businessJustification', label: 'Business Justification', type: 'textarea' },
    { key: 'deliveryDate', label: 'Delivery Date', type: 'date' },
    { key: 'isUrgent', label: 'Urgent', type: 'boolean' },
    { key: 'daysInStage', label: 'Days in stage', type: 'number', min: 0 },
    { key: 'isOverdue', label: 'Overdue', type: 'boolean' },
    { key: 'referBackCount', label: 'Refer-back count', type: 'number', min: 0 },
  ],
  filters: [
    {
      key: 'status',
      label: 'Status',
      options: [
        { value: 'draft', label: 'Draft' },
        { value: 'intake', label: 'Intake' },
        { value: 'validation', label: 'Validation' },
        { value: 'approval', label: 'Approval' },
        { value: 'sourcing', label: 'Sourcing' },
        { value: 'contracting', label: 'Contracting' },
        { value: 'po', label: 'PO' },
        { value: 'receipt', label: 'Receipt' },
        { value: 'invoice', label: 'Invoice' },
        { value: 'payment', label: 'Payment' },
        { value: 'completed', label: 'Completed' },
        { value: 'cancelled', label: 'Cancelled' },
        { value: 'referred-back', label: 'Referred back' },
      ],
      predicate: (r, v) => r.status === v,
    },
    {
      key: 'buyingChannel',
      label: 'Channel',
      options: [
        { value: 'procurement-led', label: 'Procurement-led' },
        { value: 'business-led', label: 'Business-led' },
        { value: 'direct-po', label: 'Direct PO' },
        { value: 'framework-call-off', label: 'Framework call-off' },
        { value: 'catalogue', label: 'Catalogue' },
      ],
      predicate: (r, v) => r.buyingChannel === v,
    },
  ],
};
